-- MySQL Script generated by MySQL Workbench
-- Fri May 29 16:42:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cities_test_ibfk_1` (`state_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States`
    FOREIGN KEY (`state_id`)
    REFERENCES `mydb`.`States` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Device_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Device_Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `weight` FLOAT NOT NULL,
  `height` FLOAT NOT NULL,
  `insurance_id` INT NOT NULL,
  `insurance_number` VARCHAR(45) NOT NULL,
  `heart_rate_signal_threshold` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Device_users_Insurances1_idx` (`insurance_id` ASC) VISIBLE,
  INDEX `fk_Device_Users_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Device_Users_Insurances`
    FOREIGN KEY (`insurance_id`)
    REFERENCES `mydb`.`Insurances` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Device_Users_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diseases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Document_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Document_Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Email_Reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Email_Reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_user_id` INT NOT NULL,
  `report_date` DATETIME NOT NULL,
  `emergency_contacts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Email_reports_Device_users1_idx` (`device_user_id` ASC) VISIBLE,
  INDEX `fk_Email_Reports_Emergency_Contacts1_idx` (`emergency_contacts_id` ASC) VISIBLE,
  CONSTRAINT `fk_Email_Reports_Device_Users`
    FOREIGN KEY (`device_user_id`)
    REFERENCES `mydb`.`Device_Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Email_Reports_Emergency_Contacts1`
    FOREIGN KEY (`emergency_contacts_id`)
    REFERENCES `mydb`.`Emergency_Contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Emergency_Contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emergency_Contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `relation` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Emergency_contacts_Device_users1_idx` (`device_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Emergency_Contacts_Device_Users`
    FOREIGN KEY (`device_user_id`)
    REFERENCES `mydb`.`Device_Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `path` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Heart_Rate_Signals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Heart_Rate_Signals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_report_id` INT NOT NULL,
  `time` TIME NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Heart_rate_signals_Workout_reports1_idx` (`workout_report_id` ASC) VISIBLE,
  CONSTRAINT `fk_Heart_Rate_Signals_Workout_Reports`
    FOREIGN KEY (`workout_report_id`)
    REFERENCES `mydb`.`Workout_Reports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Insurances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Personnel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `medical_speciality_id` INT NOT NULL,
  `mp_public_key` VARCHAR(200) NULL,
  `mp_access_token` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Medical_personnel_Medical_specialities1_idx` (`medical_speciality_id` ASC) VISIBLE,
  INDEX `fk_Medical_Personnel_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medical_Personnel_Medical_Specialities`
    FOREIGN KEY (`medical_speciality_id`)
    REFERENCES `mydb`.`Medical_Specialities` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Medical_Personnel_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Specialities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Phone_Numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Phone_Numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Phone_Numbers_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Phone_Numbers_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`States` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `country_region` (`country_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_States_Countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`Countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `mydb`.`User_Diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Diseases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_user_id` INT NOT NULL,
  `disease_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Device_users_has_Diseases_Diseases1_idx` (`disease_id` ASC) VISIBLE,
  INDEX `fk_Device_users_has_Diseases_Device_users1_idx` (`device_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Diseases_Device_Users`
    FOREIGN KEY (`device_user_id`)
    REFERENCES `mydb`.`Device_Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_Diseases_Diseases`
    FOREIGN KEY (`disease_id`)
    REFERENCES `mydb`.`Diseases` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `document_type_id` INT NOT NULL,
  `document_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `city_id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Users_Document_Types1_idx` (`document_type_id` ASC) VISIBLE,
  INDEX `fk_cities_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Document_Types`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `mydb`.`Document_Types` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Users_Cities`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`Cities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Workout_Exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workout_Exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Workouts_has_Exercise_Exercise1_idx` (`exercise_id` ASC) VISIBLE,
  INDEX `fk_Workouts_has_Exercise_Workouts_idx` (`workout_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workouts_Exercises_Exercise`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `mydb`.`Exercises` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Workouts_Exercises_Workouts`
    FOREIGN KEY (`workout_id`)
    REFERENCES `mydb`.`Workouts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Workout_Reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workout_Reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workout_id` INT NOT NULL,
  `execution_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Workout_reports_Workouts1_idx` (`workout_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workout_Reports_Workouts`
    FOREIGN KEY (`workout_id`)
    REFERENCES `mydb`.`Workouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workouts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_user_id` INT NOT NULL,
  `medical_personnel_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `creation_date` DATE NOT NULL,
  `difficulty` INT NOT NULL,
  `price` FLOAT NULL DEFAULT 0,
  `done` TINYINT NOT NULL,
  `rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Workouts_Device_users1_idx` (`device_user_id` ASC) VISIBLE,
  INDEX `fk_Workouts_Medical_personnel1_idx` (`medical_personnel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workouts_Device_Users`
    FOREIGN KEY (`device_user_id`)
    REFERENCES `mydb`.`Device_Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Workouts_Medical_Personnel`
    FOREIGN KEY (`medical_personnel_id`)
    REFERENCES `mydb`.`Medical_Personnel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
