
insert into Medical_Specialities (id, name) values (null, "Adicciones");
insert into Medical_Specialities (id, name) values (null, "Alergologia");
insert into Medical_Specialities (id, name) values (null, "Analitica Clinica");
insert into Medical_Specialities (id, name) values (null, "Andrologia");
insert into Medical_Specialities (id, name) values (null, "Anestesiologia");
insert into Medical_Specialities (id, name) values (null, "Angiologia");
insert into Medical_Specialities (id, name) values (null, "Cardiologia");
insert into Medical_Specialities (id, name) values (null, "Cardiologia");
insert into Medical_Specialities (id, name) values (null, "Cardiovascular");
insert into Medical_Specialities (id, name) values (null, "Cirugia");
insert into Medical_Specialities (id, name) values (null, "Cirugia Ortopedica");
insert into Medical_Specialities (id, name) values (null, "Cirugia Ortopedica y Traumatologia");
insert into Medical_Specialities (id, name) values (null, "Cirugia Plastica y Maxilofacial");
insert into Medical_Specialities (id, name) values (null, "Cirugia Toracica");
insert into Medical_Specialities (id, name) values (null, "Cirugia Vascular");
insert into Medical_Specialities (id, name) values (null, "Coronavirus");
insert into Medical_Specialities (id, name) values (null, "Dermatologia");
insert into Medical_Specialities (id, name) values (null, "Dietetica y Nutricion");
insert into Medical_Specialities (id, name) values (null, "Divulgacionmedica");
insert into Medical_Specialities (id, name) values (null, "Endocrinologia");
insert into Medical_Specialities (id, name) values (null, "Enfermedades Autoinmunes");
insert into Medical_Specialities (id, name) values (null, "Enfermedades Infecciosas");
insert into Medical_Specialities (id, name) values (null, "Enfermedades infecciosas, Enfermedades autoinmunes");
insert into Medical_Specialities (id, name) values (null, "Enfermedades Neurodegenerativas");
insert into Medical_Specialities (id, name) values (null, "Enfermedades raras");
insert into Medical_Specialities (id, name) values (null, "Epidemiologia");
insert into Medical_Specialities (id, name) values (null, "Estadistica");
insert into Medical_Specialities (id, name) values (null, "ETS");
insert into Medical_Specialities (id, name) values (null, "Farmacologia");
insert into Medical_Specialities (id, name) values (null, "Gastroenterologia");
insert into Medical_Specialities (id, name) values (null, "Genetica");
insert into Medical_Specialities (id, name) values (null, "Geriatria");
insert into Medical_Specialities (id, name) values (null, "Geriatria y Gerontologia");
insert into Medical_Specialities (id, name) values (null, "Gestion Sanitaria");
insert into Medical_Specialities (id, name) values (null, "Ginecologia");
insert into Medical_Specialities (id, name) values (null, "Hematologia");
insert into Medical_Specialities (id, name) values (null, "Hepatologia");
insert into Medical_Specialities (id, name) values (null, "Infantil");
insert into Medical_Specialities (id, name) values (null, "Infecciones");
insert into Medical_Specialities (id, name) values (null, "Inmunologia");
insert into Medical_Specialities (id, name) values (null, "Investigacion");
insert into Medical_Specialities (id, name) values (null, "Lipidologia");
insert into Medical_Specialities (id, name) values (null, "Medicinade Familia");
insert into Medical_Specialities (id, name) values (null, "Medicinade Urgencia");
insert into Medical_Specialities (id, name) values (null, "Medicina Deportiva");
insert into Medical_Specialities (id, name) values (null, "Medicina Familiar");
insert into Medical_Specialities (id, name) values (null, "Medicina General");
insert into Medical_Specialities (id, name) values (null, "Medicina Interna");
insert into Medical_Specialities (id, name) values (null, "Medicina Nuclear");
insert into Medical_Specialities (id, name) values (null, "Medicina Personalizada");
insert into Medical_Specialities (id, name) values (null, "Medicina Preventiva");
insert into Medical_Specialities (id, name) values (null, "Medicina Primaria");
insert into Medical_Specialities (id, name) values (null, "Medicina Regenerativa");
insert into Medical_Specialities (id, name) values (null, "Medicina Tropical");
insert into Medical_Specialities (id, name) values (null, "Medicina de Urgencias");
insert into Medical_Specialities (id, name) values (null, "Miscelanea");
insert into Medical_Specialities (id, name) values (null, "Nefrologia");
insert into Medical_Specialities (id, name) values (null, "Neumologia");
insert into Medical_Specialities (id, name) values (null, "Neurologia");
insert into Medical_Specialities (id, name) values (null, "Nutricion");
insert into Medical_Specialities (id, name) values (null, "Obstetricia");
insert into Medical_Specialities (id, name) values (null, "Obstetricia y Ginecologia");
insert into Medical_Specialities (id, name) values (null, "Odontologia");
insert into Medical_Specialities (id, name) values (null, "Oftalmologia");
insert into Medical_Specialities (id, name) values (null, "Oncologia");
insert into Medical_Specialities (id, name) values (null, "Oncologia Radioterapica");
insert into Medical_Specialities (id, name) values (null, "Otorrinolaringologia");
insert into Medical_Specialities (id, name) values (null, "Pediatria");
insert into Medical_Specialities (id, name) values (null, "Politica Sanitaria");
insert into Medical_Specialities (id, name) values (null, "Psicologia");
insert into Medical_Specialities (id, name) values (null, "Psiquiatria");
insert into Medical_Specialities (id, name) values (null, "Psiquiatria y Psicologia");
insert into Medical_Specialities (id, name) values (null, "Pulmonar");
insert into Medical_Specialities (id, name) values (null, "Radiologia");
insert into Medical_Specialities (id, name) values (null, "Rehabilitacin");
insert into Medical_Specialities (id, name) values (null, "Renal");
insert into Medical_Specialities (id, name) values (null, "Reumatologia");
insert into Medical_Specialities (id, name) values (null, "Saludmental");
insert into Medical_Specialities (id, name) values (null, "SaludPublica");
insert into Medical_Specialities (id, name) values (null, "Sexologia");
insert into Medical_Specialities (id, name) values (null, "Trasplante");
insert into Medical_Specialities (id, name) values (null, "Trasplantes");
insert into Medical_Specialities (id, name) values (null, "Traumatologia y Ortopedia");
insert into Medical_Specialities (id, name) values (null, "Urgencias");
insert into Medical_Specialities (id, name) values (null, "Urologia");
insert into Medical_Specialities (id, name) values (null, "Virologia");
insert into Medical_Specialities (id, name) values (null, "Zoonosis");
insert into Medical_Specialities (id, name) values (null, "Otra");
