insert into Insurances (id, name) values (null, "Aca Salud");
insert into Insurances (id, name) values (null, "Accord Salud");
insert into Insurances (id, name) values (null, "Alta Salud");
insert into Insurances (id, name) values (null, "Amur Medicina Prepaga");
insert into Insurances (id, name) values (null, "Apres Salud");
insert into Insurances (id, name) values (null, "Bristol Medicine");
insert into Insurances (id, name) values (null, "Casa Salud");
insert into Insurances (id, name) values (null, "CEMIC Plan de Salud");
insert into Insurances (id, name) values (null, "COBERMED");
insert into Insurances (id, name) values (null, "Federada Salud");
insert into Insurances (id, name) values (null, "FEMÉDICA");
insert into Insurances (id, name) values (null, "Galeno");
insert into Insurances (id, name) values (null, "GEA Cobertura de Salud");
insert into Insurances (id, name) values (null, "Hominis");
insert into Insurances (id, name) values (null, "Medife");
insert into Insurances (id, name) values (null, "Medicus");
insert into Insurances (id, name) values (null, "Nobis Salud");
insert into Insurances (id, name) values (null, "OMINT");
insert into Insurances (id, name) values (null, "OSDE");
insert into Insurances (id, name) values (null, "Parque Salud");
insert into Insurances (id, name) values (null, "Plan de salud del Hospital Alemán");
insert into Insurances (id, name) values (null, "Plan de salud del Hospital Italiano");
insert into Insurances (id, name) values (null, "Prevención Salud");
insert into Insurances (id, name) values (null, "SanCor Salud");
insert into Insurances (id, name) values (null, "Swiss Medical");
insert into Insurances (id, name) values (null, "UAI Salud");
insert into Insurances (id, name) values (null, "William Hope Salud");
insert into Insurances (id, name) values (null, "Otra");